### ISSUE TITLE
JetBrains support posibilities

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/Community#1]
## Asked for

- merchandize options, put out to community to ask, what they want

## Confirmed Options

- possibility of meetup since 2018 in their new spaces, or sponsoring in cowork centers
- internal-company hackaton, ask @chemix 
- social promo of 
- videos in Czech language, cc @tomasfejfar 
- support [program for lectors](https://www.jetbrains.com/support/community/?fromMenu#section=classroom), cc @tomasfejfar 
- possible space in Munich, for meetups and so

## Todo

- [ ] group meetup with @tomasvotruba and @chemix about media-technics support - camera, microphone...

## Done

- [x] **10. 5. initial meetup in Prague**, with Martin Pavlů, @tomasvotruba and @tomasfejfar about possible mutual support between @pehapkari and @jetbrains

## Where to go next

- @jakubkratina came with idea to create a live-stream with the speaker instead, it's much easier than to travel from Russia;

    - [ ] todo @tomasvotruba - ask Martin

**Comment by tomasfejfar** [comment]
I'm not sure what `community-cherry-pickup merge` means. Is it `community cherry-picked merch(andise)`? In that case `Merchandise selected by community` is the correct english description - they are willing to supply some merchandising if we tell them what we want (I said at the meeting that I, personally, would love a PhpStorm T-shirt) - stickers weren't such success earlier, licenses are great. Some more tangible things would be great for various competitions IMHO - like mugs, mousepads, keychains, etc. Or some jetbrains-themed gadgets for special occasions.

**Comment by TomasVotruba** [comment]
Yes, you are correct. "merch" it is. I will ask Martin about list of them.

**Comment by tomasfejfar** [comment]
OK, no worries. It happens to me as well, that I use different same-sounding word even though I know it means something different. I think those are called brain-farts :)

**Comment by TomasVotruba** [comment]
Thanks for uderstanding.

Well, I used it as joke before and sticked with me in useless contexts :)

**Comment by TomasVotruba** [comment]
I've updated the description.

Btw, možná bychom měli psát česky, co? Když je tady všechno česky a týká se to česky mluvících lidí. :D 

Blbě se mi to překládá z těch českých emailů.

**Comment by TomasVotruba** [comment]
Tak swagu bylo nakonec natolik málo a nebylo by efektivní to řešit na FB, že z toho udělám jako surprise balíčky pro speakry.
