### ISSUE TITLE
Slovenská komunita - zážeh

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/Community#8]
Poznáky z volání s @edobarnas

## Todo

- [x] propojit Edu s Juliem na FB - @tomasvotruba
- [ ] napísat na slack - @edobarans

## Co obnáší sraz?

- [ ] sehnat prostory pro 15-25 lidí
    - [ ] prostor s Wifi, aby šlo nahrávat livestream přes Facebook Page appku na mobilu
    - [ ] pivko výhodou, nikoli nutností; drobné zákusky výhodou, nikoli nutností
    - [ ] v nějaké firmě nebo coworkingu; spíš než v hospodě nebo čajovně, není nutností
    - [ ] s projektorem
- [ ] sehnat 2 speakry
    - [ ] 2 předášky v délce 15-25 minut
- [ ] hodit na akci na [FB](https://www.facebook.com/pehapkari/) a [Twitter](https://twitter.com/pehapkari)
- [ ] před akcí [poslat newsletter](https://pehapkari.cz/#newsletter)

### Typický sraz

- 18 open door
- 18:30 úvítání + 1. talk
- 19 přesátvka
- 20:00 2. talk
- 20:30 pokec, pivko
- 21:30 přesun do hospody

**Comment by jakubkratina** [comment]
Před tím, než se tohle pořádne vykopne, tak bych navrhoval doklepnout financování a nastavil to, aby se to mohlo na SK "spustit" rovnou s tím modelem viz https://github.com/pehapkari/Community/issues/2

**Comment by TomasVotruba** [comment]
@jakubkratina To by bylo určitě fajn, jen je potřeba se na tom dohodnout ve více lidech. Zatím jsem se tam ale vyjádřil jen já.

**Comment by Tuzex** [comment]
Ahojte chalani, prestudujem a dam vyjadrenie. :)

**Comment by TomasVotruba** [comment]
Ahoj Edo, jak to vypadá? 

Nechci na tebe tlačit, jen je půl roku pryč a mám trochu obavy, aby to nevyšumělo.

Můžeme s něčím pomoci?

**Comment by VeeeneX** [comment]
Priestory by možno aj mohli byť v napríklad v progressbare (trebalo by vyzistiť pretože sú tam jskari :D)?

**Comment by TomasVotruba** [comment]
Fajné :). Můžes se prosím zeptat či by to šlo nějaký den po 18 hod. na cca 3 hoďky?

Nevím jestli to má Eda vymyšlené na konkrétní den, ale úterý, čtvrtek nebo pátek by myslím šel.

**Comment by Tuzex** [comment]
Ahojte chalani. Velmi ma mrzi momentalne neaktivita. Moje casove moznosti su aktualne (dufam ze kratkodobo) mizerne.

Kazdopadne sa nechem vyhovarat. Dakujem za pripomenutie a tesim sa aj novym moznostiam. Pokusim sa zajtra pripravit nastrel textu na slack a verim ze sa najde viac mohykanov. :)

Este raz vdaka vsetkym.

**Comment by TomasVotruba** [comment]
Outdated
